#!/bin/sh
DIR=`dirname $0`/..
JARS=$DIR/lib/copris-all-v2-2-2.jar
[ -n "$JAVA_OPTS" ] || export JAVA_OPTS="-Xmx2000M -Xms512M -Xss64M -XX:-UseGCOverheadLimit"
# [ -n "$JAVA_OPTS" ] || export JAVA_OPTS="-Xmx2000M -Xms512M -Xss64M -agentlib:hprof=cpu=samples,depth=16,file=java.prof"
exec scala -cp .:classes:$JARS $* 2>&1
