#!/bin/sh
DIR=`dirname $0`/..
JARS=$DIR/lib/copris-v1-0-2.jar:$DIR/lib/sugar-v1-15-1.jar:$DIR/lib/org.sat4j.core.jar
[ -n "$JAVA_OPTS" ] || export JAVA_OPTS="-Xmx2000M -Xms64M -Xss64M"
# [ -n "$JAVA_OPTS" ] || export JAVA_OPTS="-Xmx2000M -Xms64M -Xss64M -agentlib:hprof=cpu=samples,depth=16,file=java.prof"
scala -cp .:classes:$JARS $* 2>&1

