#!/bin/sh
DIR=`dirname $0`/..
JARS=$DIR/lib/copris-v2-0-0.jar:$DIR/lib/sugar-v2-0-0.jar:$DIR/lib/org.sat4j.core.jar
[ -n "$JAVA_OPTS" ] || export JAVA_OPTS="-Xmx2000M -Xms512M -Xss64M -XX:-UseGCOverheadLimit"
# [ -n "$JAVA_OPTS" ] || export JAVA_OPTS="-Xmx2000M -Xms512M -Xss64M -agentlib:hprof=cpu=samples,depth=16,file=java.prof"
scala -cp .:classes:$JARS $* 2>&1

