#!/bin/sh
DIR=`dirname $0`/..
JARS=$DIR/lib/copris-v2-0-0.jar:$DIR/lib/sugar-v2-0-0.jar:$DIR/lib/org.sat4j.core.jar
exec scalac -optimize -cp .:classes:$JARS -d classes $*
# exec fsc -optimize -cp .:classes:$JARS -d classes $*
